### ISSUE TITLE
耳机接口插入耳麦后，首次播放声音后出现爆炸声然后没有音乐输出到耳机的问题。

### ISSUE THREAD

**Issue by ice-forever** [Forever331/Dell_G5_5500_Hackintosh#5]
经过尝试，在mac11.6的版本中，使用扬声器可以正常播放声音，插入耳机后，开始播放声音仅能正常播放2~3秒，之后耳机就没有声音了，请问大佬您有解决思路么。电脑配置与您测试的系统配置相同。

**Comment by Forever331** [comment]
你好  请问出现爆炸声后 系统信息内与音频相关设备是否消失
或者 Hackintool的音频选项是否能看到插口类型的音频输出或输入
可以考虑修改layout ID或自行仿冒驱动

**Comment by Forever331** [comment]
等待解决 如果需要可以使用Type-C或者USB声卡

**Comment by ice-forever** [comment]
感谢您的解答，经过我的测试，发现蓝牙连接的耳机可以正常使用，推测是耳机不兼容的问题或者是电脑耳机接口的问题。内置扬声器和蓝牙耳机可以正常工作。
