### ISSUE TITLE
Not booting

### ISSUE THREAD

**Issue by Ocin4ever** [Forever331/Dell_G5_5500_Hackintosh#6]
Hello,
Thank you for efi but it won't boot as long as gpu acceleration is active with (-igfxvesa).
Thank you for your help

**Comment by Forever331** [comment]
Hello, after testing and enabling (- igfxvesa), the system can be started normally

![](https://s3.bmp.ovh/imgs/2022/09/17/4b7a59f16f57b897.png)

**Comment by Ocin4ever** [comment]
hello, my problem is when I start with your efi, it is stuck in verbose mode and displays: gioscreenlockstate 3. However if I add the argument (-igfxvesa), which disables graphics acceleration, mac os starts normally but does not provide only 7mb of vram for the uhd 630.
If you don't understand i can send you pictures.

Thank you a lot for your help because I've been trying to make a hackintosh for 1 year without success.

Ps: can you tel me the bios version and the configuration please

**Comment by Forever331** [comment]
Hello, the bios version is 1.19.0, and the computer configuration details are on the home page.
But I didn't encounter this problem in the initial configuration, so I may not be able to help you.
sorry.😣

**Comment by Ocin4ever** [comment]
Excuse me for disturbing you one last time but could you take a picture of the different settings that you have changed in the bios because I think my problem comes from there and I don't see the bios configuration on your guide.  thank you so much

**Comment by Forever331** [comment]
https://s3.bmp.ovh/imgs/2022/09/19/f037064f35115667.jpg
https://s3.bmp.ovh/imgs/2022/09/19/f2d31e800283103f.jpg
https://s3.bmp.ovh/imgs/2022/09/19/7938d17a42f7968f.jpg
https://s3.bmp.ovh/imgs/2022/09/19/a592f79cb32f6ac4.jpg
https://s3.bmp.ovh/imgs/2022/09/19/a9c7dcc5524ec629.jpg
Hello, this is the bios setting, but I can't ensure it is completely effective
Good luck.

**Comment by Ocin4ever** [comment]
Hello, 
I progress in the fix but can you send me the efi for big sur version 0.7.3 as you mentioned in your article.
Thank you

**Comment by Forever331** [comment]
Sorry, the efi version 0.7.3 is not saved, you can find the modified file through commits
